sudo: false
language: scala
jdk:
  - oraclejdk8
before_script:
  - echo -e 'addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")\n\naddSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.2.2")' > project/tmpCoverage.sbt
script:
  - sbt clean coverage test coverageReport coverageAggregate
after_success:
  - sbt coveralls
