sudo: false
language: scala
jdk:
  - openjdk8
jobs:
  include:
    - stage: Tests
      script: sbt clean coverage test coverageReport coverageAggregate coveralls
    - stage: "Formatting and Documentation"
      script: sbt clean scalafmtSbtCheck scalafmtCheckAll
    - script: sbt clean makeSite
