name: Release

on: workflow_dispatch

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sbt -Dsbt.color=true -Dsbt.supershell=false "release with-defaults"
