name: Release

on: workflow_dispatch

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          - git config --global user.name "Michael Krolikowski"
          - git config --global user.email "mkroli@yahoo.de"
          - sbt -Dsbt.color=true -Dsbt.supershell=false "release with-defaults"
